######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 13 11:53:53 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyMainWindow.h
SOURCES += main.cpp
